services:
  worker:
    build:
      context: ${PHP_DIR_ABS}
      target: worker
    depends_on:
      php:
        condition: service_healthy
        restart: true
    volumes:
      - ${PHP_DIR_ABS}/supervisor/:/etc/supervisor/:ro
      - ${XO_ROOT_DIR}/${XO_PHP_ROOT}:/var/www/html/:rw
      - ${XO_CONFIG_DIR}/composer_tmp:/composer/:rw

    env_file:
      - ${XO_ROOT_DIR}/.env
      - ${XO_ROOT_DIR}/.env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "supervisorctl", "-c", "/etc/supervisor/supervisord.conf", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  php:
    user: ${USER_UID}:${USER_GID}
    build:
      context: ${PHP_DIR_ABS}
      target: dev
    ports:
      - "80:80"
    volumes:
      - ${XO_ROOT_DIR}/${XO_PHP_ROOT}:/var/www/html/:rw
    env_file:
      - ${XO_ROOT_DIR}/.env
      - ${XO_ROOT_DIR}/.env.local
      - ${XO_CONFIG_DIR}/composer_tmp:/composer/:rw

    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  default:
    external: true
    name: ${XO_PROJECT_NAME}
